apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradinglab-ui
  namespace: tradinglab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tradinglab-ui
  template:
    metadata:
      labels:
        app: tradinglab-ui
    spec:
      containers:
        - name: tradinglab-ui
          image: ${REGISTRY}/tradinglab-ui:${VERSION}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 90
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tradinglab-ui
  namespace: tradinglab
spec:
  selector:
    app: tradinglab-ui
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tradinglab-ui-hpa
  namespace: tradinglab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tradinglab-ui
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60