apiVersion: v1
kind: Secret
metadata:
  name: tradinglab-credentials
  namespace: tradinglab
type: Opaque
data:
  alpaca_api_key: PKSAWIF5A6KQYE0HX5NY
  alpaca_api_secret: P3Q80cnhwh4p59BWfJdIj3uQMaX674JJY8HnDJFl