# k8s/market-data-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  namespace: tradinglab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      labels:
        app: market-data-service
    spec:
      containers:
        - name: market-data-service
          image: ${REGISTRY}/market-data-service:${VERSION}
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: events-config
                  key: nats-url
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tradinglab-credentials
                  key: alpha_vantage_api_key
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: events-config
                  key: events-log-level
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  namespace: tradinglab
spec:
  selector:
    app: market-data-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP