# kube/market-data/market-data.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  namespace: tradinglab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      labels:
        app: market-data-service
    spec:
      containers:
        - name: market-data-service
          image: ${REGISTRY}/market-data-service:${VERSION}
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: events-config
                  key: nats-url
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tradinglab-credentials
                  key: alpaca_api_key
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: tradinglab-credentials
                  key: alpaca_api_secret
            - name: ALPACA_LIVE_TRADING
              value: "false"
            - name: POLLING_INTERVAL
              value: "60s"
            - name: WATCH_TICKERS
              value: "SPY,AAPL,MSFT,GOOGL,AMZN"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: events-config
                  key: events-log-level
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  namespace: tradinglab
spec:
  selector:
    app: market-data-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP