apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradinglab-service
  namespace: tradinglab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradinglab-service
  template:
    metadata:
      labels:
        app: tradinglab-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: tradinglab-service
          image: ${REGISTRY}/tradinglab-service:${VERSION}
          ports:
            - containerPort: 50052
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tradinglab-credentials
                  key: alpaca_api_key
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: tradinglab-credentials
                  key: alpaca_api_secret
            - name: ALPACA_LIVE_TRADING
              value: "false"
            - name: CACHE_DIR
              value: "/app/data_cache"
            - name: GRPC_PORT
              value: "50052"
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: events-config
                  key: nats-url
            - name: WATCH_TICKERS
              value: "SPY,AAPL,MSFT,GOOGL,AMZN"
            - name: TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: timezone-config
                  key: TIMEZONE
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data-cache
              mountPath: /app/data_cache
          readinessProbe:
            exec:
              command: ["python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:50052'); channel.close()"]
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:50052'); channel.close()"]
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data-cache
          emptyDir: {}